export const ROUTES = {
	LOGIN: '/login',
	RESET_PASSWORD: '/reset-password',
	HOME: '/',
	COMMUNITY: '/community',
	RECIPES: '/community/recipes',
	BLOGS: '/community/blogs',
	BOOKMARKS: '/bookmarks',
	ABOUT_US: '/about',
	CONTACT_US: '/contact',
	GUIDELINE: '/guideline',
	FAQS: '/faqs',
	SEND_FEEDBACK: '/send-feedback',
	SETTINGS: '/settings',
	REPORT_HISTORY: '/report-history',
	PRIVACY_POLICY: '/privacy-policy',
	TERMS_OF_SERVICE: '/terms',
} as const
